const express = require('express');
const path = require('path');
const app = express();
const fs = require('fs');
const config = require('./config');
require('dotenv').config();

// Serve static files from the "dist" directory generated by the Angular build
app.use(express.static(path.join(__dirname, '../../dist/devui-admin')));
console.log('process.env.API_URL',process.env.API_URL);
// Optional: Add your API routes here if you have any
// app.use('/api', require('./your-api-routes'));
app.use('/config', (req, res) => res.send(config));
// Serve the Angular application for all other routes
app.get('*', (req, res) => {
    // res.sendFile(path.join(__dirname, '../dist/devui-admin/index.html'));
    const indexPath = path.join(__dirname, '../../dist/devui-admin', 'index.html');
    let content = fs.readFileSync(indexPath, 'utf8');
    // Injecting the script
    // content = content.replace('</body>', `<script>localStorage.setItem('API_URL', '${process.env.API_URL}');</script></body>`);
    // console.log('process.env.API_URL',process.env.API_URL);

    res.send(content);
});

// Start the server
const port = process.env.PORT || 3001;
app.listen(port, () => {
  console.log(`Server started on port ${port}`);
});

module.exports = app;